{% set name = "testbook" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nteract/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 879cb2104d7a198e0311c37a3a775f5b96013a8d34473228e87c3309e5a454cb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - nbformat >=5.0.4
    - nbclient >=0.4.0

test:
  requires:
    - pip
  imports:
    - testbook
  commands:
    - pip check

about:
  home: https://github.com/nteract/testbook
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unit test your Jupyter Notebooks the right way

  # The remaining entries in this section are optional, but recommended.
  description: |
    testbook is a unit testing framework extension for testing code in Jupyter Notebooks.

    Previous attempts at unit testing notebooks involved writing the tests in the notebook 
    itself. However, testbook will allow for unit tests to be run against notebooks in 
    separate test files, hence treating .ipynb files as .py files.

    testbook helps you set up conventional unit tests for your Jupyter Notebooks.
  doc_url: https://testbook.readthedocs.io/
  dev_url: https://github.com/nteract/testbook

extra:
  recipe-maintainers:
    - fcollonval
    - MSeal
    - rohitsanj
